### ISSUE TITLE
BUG #3| Import Data doubles students data

### ISSUE THREAD

**Issue by rexuswolf** [RexusWolf/IS#16]
We're looking at it.

**Comment by RexusWolf** [comment]
Solved. Iterators in SearchStudent() (ID_001) were wrong, moving through the list from its end to...its end++.

**Comment by RexusWolf** [comment]
Solved. Iterators in SearchStudent() (ID_001) were wrong, moving through the list from its end to...its end++.

**Comment by rexuswolf** [comment]
Solved. Had to add a binary file reading (b.read) before the while loop.
